version: "3.3"
services:
    skport-auto-login:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: skport-auto-login
        env_file:
            - .env




